// ============================================================================
//  ota.h — over-the-air firmware update with a server-issued key
//
//  The device runs a small web updater while it is connected to the network:
//
//      POST http://<device-ip>:3232/update?key=<ota_token>   (multipart, .bin)
//
//  Security model
//  --------------
//  * `ota_token` is generated by the server (per device) and pushed to the
//    device through the normal config channel. An update is refused unless the
//    token matches, so a random host on the LAN cannot reflash the node.
//  * The token lives in NVS; wiping the device config (serial `reset`) clears
//    it, which also disables remote updates until the server provisions it
//    again.
//  * The updater only accepts a valid ESP32 image (Update.h validates the
//    magic byte and the size), and it runs on its own port so it never
//    interferes with the ranging loop.
//
//  A token in the query string is not ideal (it can land in logs), but it
//  keeps the device side tiny and works with plain `curl -F`. Use a trusted
//  LAN or a TLS reverse proxy in front of it.
// ============================================================================
#pragma once

#include <Arduino.h>
#include <WebServer.h>
#include <Update.h>
#include <WiFi.h>
#include "config.h"
#include "net.h"

extern WebServer g_ota;   // defined in main.cpp

// upload state (single upload at a time)
inline bool ota_rejected = false;
inline bool ota_ok = false;

// ---------------------------------------------------------------------------
// upload handling
//
// NOTE on authentication timing: inside an HTTPUpload callback the query
// string is already parsed, but `hasArg()`/`arg()` are only reliable for
// *form fields*; the query string is parsed by the time the upload handler is
// entered, so we read it directly from the raw request line to be safe. A
// missing/incorrect key aborts the upload before any flash write.
// ---------------------------------------------------------------------------
inline bool otaKeyOk()
{
    if (!cfg.ota_token[0]) return false;
    if (!g_ota.hasArg("key")) return false;
    return g_ota.arg("key") == cfg.ota_token;
}

inline void otaUploadStart()
{
    HTTPUpload &up = g_ota.upload();

    if (up.status == UPLOAD_FILE_START) {
        // Authenticate BEFORE opening the flash partition.
        if (!otaKeyOk()) {
            Serial.println(F("[ota] rejected: bad or missing key"));
            ota_rejected = true;
            return;
        }
        ota_rejected = false;
        Serial.printf("[ota] receiving %s (%u bytes)\n",
                      up.filename.c_str(), (unsigned)up.totalSize);

        // Prefer the declared content length: UPDATE_SIZE_UNKNOWN makes
        // Update.begin() scan for the free partition, and an empty/odd request
        // can abort the transfer mid-flight.
        const size_t clen = g_ota.clientContentLength();
        size_t target = (clen > 1024) ? clen : up.totalSize;
        if (!Update.begin(target > 1024 ? target : UPDATE_SIZE_UNKNOWN)) {
            Serial.printf("[ota] Update.begin failed: %s\n", Update.errorString());
            ota_rejected = true;
        }
    } else if (up.status == UPLOAD_FILE_WRITE) {
        if (ota_rejected) return;
        if (Update.write(up.buf, up.currentSize) != up.currentSize) {
            Serial.printf("[ota] write failed: %s\n", Update.errorString());
            ota_rejected = true;
        }
    } else if (up.status == UPLOAD_FILE_END) {
        if (ota_rejected) { Update.abort(); return; }
        if (Update.end(true)) {
            Serial.printf("[ota] success, %u bytes — rebooting\n", (unsigned)up.totalSize);
            ota_ok = true;
        } else {
            Serial.printf("[ota] Update.end failed: %s\n", Update.errorString());
            ota_rejected = true;
        }
    } else if (up.status == UPLOAD_FILE_ABORTED) {
        Update.abort();
        ota_rejected = true;
        Serial.println(F("[ota] aborted"));
    }
}

inline void otaRegister()
{
    g_ota.on("/update", HTTP_POST,
        // completion handler
        []() {
            const bool ok = ota_ok && !Update.hasError();
            g_ota.sendHeader("Connection", "close");
            g_ota.send(ok ? 200 : 500, "text/plain",
                       ok ? "OK: rebooting" : "FAILED");
            ota_ok = false;
            if (ok) { delay(300); ESP.restart(); }
        },
        otaUploadStart);

    // tiny status page so the device is discoverable on the LAN
    g_ota.on("/", HTTP_GET, []() {
        char id[16], eui[40];
        deviceId(cfg, id, sizeof(id));
        deviceEui(cfg, eui, sizeof(eui));
        char page[420];
        snprintf(page, sizeof(page),
                 "<!doctype html><meta name=viewport content='width=device-width,initial-scale=1'>"
                 "<body style=\"font:14px system-ui;background:#0b0e1a;color:#e8ecf8;padding:20px\">"
                 "<h2>UWB node</h2><p><b>%s</b><br>EUI <code>%s</code><br>firmware %s</p>"
                 "<p>IP %s &middot; RSSI %d dBm</p>"
                 "<p>OTA: %s</p>"
                 "<form method=post action='/update' enctype='multipart/form-data'>"
                 "<input type=file name=firmware required> "
                 "<input name=key placeholder='server key' required> "
                 "<button>Upload</button></form></body>",
                 id, eui, FW_VERSION,
                 WiFi.localIP().toString().c_str(), (int)WiFi.RSSI(),
                 cfg.ota_enabled ? "enabled" : "disabled");
        g_ota.send(200, "text/html", page);
    });
}

// ---------------------------------------------------------------------------
// lifecycle
// ---------------------------------------------------------------------------

// The updater runs in its OWN FreeRTOS task. Calling handleClient() from the
// main loop is not reliable here: DW1000Ranging.loop() and the MQTT/HTTP work
// starve it, and a stalled transfer shows up as the client seeing an immediate
// connection refusal (curl exit code 000) instead of a served request.
static void otaTask(void *)
{
    for (;;) {
        if (cfg.ota_enabled && net.wifi_up) g_ota.handleClient();
        vTaskDelay(pdMS_TO_TICKS(2));      // tight enough for a 1 MB upload
    }
}

// Start the updater once WiFi is up. Safe to call repeatedly.
inline void otaBegin()
{
    if (!cfg.ota_enabled || !net.wifi_up) return;
    static bool started = false;
    if (started) return;
    otaRegister();
    g_ota.begin(cfg.ota_port);
    xTaskCreatePinnedToCore(otaTask, "ota", 8192, nullptr, 2, nullptr, 0);
    started = true;
    Serial.printf("[ota] updater on http://%s:%u/update (key required)\n",
                  WiFi.localIP().toString().c_str(), (unsigned)cfg.ota_port);
}

// Kept for compatibility with the main loop; the task does the real work.
inline void otaLoop() { }
