// ============================================================================
//  ota.h — over-the-air firmware update, with a server-issued key
//
//  Two independent paths, both key-protected:
//
//  1. PULL (primary, recommended)
//     The device asks the server for the newest image and installs it itself:
//
//         GET  <server>/api/v1/ota/check?device=<id>&key=<key>
//         POST <server>/api/v1/ota/ack   {"device":..,"key":..,"status":..}
//
//     A pull is far more robust on this hardware than a push: the ESP32
//     WebServer buffers request bodies in RAM and drops a ~1 MB multipart POST
//     before the handler even runs (observed: the device logs nothing and the
//     client sees a connection reset). Downloading as the client avoids that
//     entirely, and HTTPUpdate streams the image straight into the OTA
//     partition.
//
//  2. PUSH (fallback, for a laptop on the same LAN)
//     The device also runs a small web updater:
//         POST http://<device-ip>:3232/update?key=<key>   (multipart .bin)
//     Guarded by the same key, which lives in NVS.
//
//  Security model
//  --------------
//  * the key is generated by the server (per device) and pushed through the
//    normal config channel; nothing is installed without it
//  * a wipe (`reset` on the serial menu) clears the key, disabling remote
//    updates until the server provisions the device again
// ============================================================================
#pragma once

#include <Arduino.h>
#include <WebServer.h>
#include <Update.h>
#include <WiFi.h>
#include <HTTPClient.h>
#include <HTTPUpdate.h>
#include "config.h"
#include "net.h"

extern WebServer g_ota;   // defined in main.cpp

// upload state (single upload at a time)
static bool ota_rejected = false;
static bool ota_ok = false;

// pull state
static void otaReport(bool ok, const String &msg);
static uint32_t ota_last_check_ms = 0;
static const uint32_t OTA_CHECK_INTERVAL_MS = 60000;   // ask every minute

// ---------------------------------------------------------------------------
// push: web updater on the device
// ---------------------------------------------------------------------------
inline bool otaKeyOk()
{
    if (!cfg.ota_token[0]) return false;
    if (!g_ota.hasArg("key")) return false;
    return g_ota.arg("key") == cfg.ota_token;
}

inline void otaUploadStart()
{
    HTTPUpload &up = g_ota.upload();

    if (up.status == UPLOAD_FILE_START) {
        // Authenticate BEFORE opening the flash partition.
        if (!otaKeyOk()) {
            Serial.println(F("[ota] push rejected: bad or missing key"));
            ota_rejected = true;
            return;
        }
        ota_rejected = false;
        Serial.printf("[ota] push: receiving %s (%u bytes)\n",
                      up.filename.c_str(), (unsigned)up.totalSize);

        const size_t clen = g_ota.clientContentLength();
        size_t target = (clen > 1024) ? clen : up.totalSize;
        if (!Update.begin(target > 1024 ? target : UPDATE_SIZE_UNKNOWN)) {
            Serial.printf("[ota] Update.begin failed: %s\n", Update.errorString());
            ota_rejected = true;
        }
    } else if (up.status == UPLOAD_FILE_WRITE) {
        if (ota_rejected) return;
        if (Update.write(up.buf, up.currentSize) != up.currentSize) {
            Serial.printf("[ota] write failed: %s\n", Update.errorString());
            ota_rejected = true;
        }
    } else if (up.status == UPLOAD_FILE_END) {
        if (ota_rejected) { Update.abort(); return; }
        if (Update.end(true)) {
            Serial.printf("[ota] push complete, %u bytes — rebooting\n",
                          (unsigned)up.totalSize);
            ota_ok = true;
        } else {
            Serial.printf("[ota] Update.end failed: %s\n", Update.errorString());
            ota_rejected = true;
        }
    } else if (up.status == UPLOAD_FILE_ABORTED) {
        Update.abort();
        ota_rejected = true;
        Serial.println(F("[ota] push aborted"));
    }
}

inline void otaRegister()
{
    g_ota.on("/update", HTTP_POST,
        []() {
            // Report the real outcome. Update.hasError() is false when no
            // upload happened at all, so it must not be used alone: doing so
            // made an empty POST look successful and reboot the node.
            const bool ok = ota_ok && !Update.hasError();
            g_ota.sendHeader("Connection", "close");
            g_ota.send(ok ? 200 : 500, "text/plain", ok ? "OK: rebooting" : "FAILED");
            ota_ok = false;
            if (ok) { delay(300); ESP.restart(); }
        },
        otaUploadStart);

    g_ota.on("/", HTTP_GET, []() {
        char id[16], eui[40];
        deviceId(cfg, id, sizeof(id));
        deviceEui(cfg, eui, sizeof(eui));
        char page[520];
        snprintf(page, sizeof(page),
                 "<!doctype html><meta name=viewport content='width=device-width,initial-scale=1'>"
                 "<body style=\"font:14px system-ui;background:#0b0e1a;color:#e8ecf8;padding:20px\">"
                 "<h2>UWB node</h2><p><b>%s</b><br>EUI <code>%s</code><br>firmware %s</p>"
                 "<p>IP %s &middot; RSSI %d dBm</p>"
                 "<p>Server-pull OTA: %s</p>"
                 "<form method=post action='/update' enctype='multipart/form-data'>"
                 "<input type=file name=firmware required> "
                 "<input name=key placeholder='server key' required> "
                 "<button>Upload</button></form></body>",
                 id, eui, FW_VERSION,
                 WiFi.localIP().toString().c_str(), (int)WiFi.RSSI(),
                 cfg.ota_enabled ? "enabled" : "disabled");
        g_ota.send(200, "text/html", page);
    });
}

// ---------------------------------------------------------------------------
// pull: ask the server whether a newer image exists
// ---------------------------------------------------------------------------
inline void otaCheckNow(bool force = false)
{
    if (!cfg.ota_enabled || !net.wifi_up || cfg.server_url[0] == 0) return;
    if (!cfg.ota_token[0]) return;
    if (!force && millis() - ota_last_check_ms < OTA_CHECK_INTERVAL_MS) return;
    ota_last_check_ms = millis();

    char id[16];
    deviceId(cfg, id, sizeof(id));

    char url[220];
    snprintf(url, sizeof(url), "%s/api/v1/ota/check?device=%s&key=%s",
             cfg.server_url, id, cfg.ota_token);

    HTTPClient http;
    if (!http.begin(url)) return;
    http.setTimeout(6000);
    const int code = http.GET();
    if (code == 200) {
        String body = http.getString();
        // tiny payload: {"ok":true,"update":true,"url":"...","version":"1.0.5"}
        if (body.indexOf("\"update\":true") >= 0) {
            int u = body.indexOf("\"url\":\"");
            int v = body.indexOf("\"version\":\"");
            String dl, ver;
            if (u >= 0) { int e = body.indexOf('"', u + 7); dl = body.substring(u + 7, e); }
            if (v >= 0) { int e = body.indexOf('"', v + 11); ver = body.substring(v + 11, e); }

            Serial.printf("[ota] server offers %s — downloading\n", ver.c_str());
            http.end();

            WiFiClient client;
            t_httpUpdate_return r = httpUpdate.update(client, dl);
            switch (r) {
            case HTTP_UPDATE_FAILED:
                Serial.printf("[ota] pull failed: %s\n",
                              httpUpdate.getLastErrorString().c_str());
                otaReport(false, httpUpdate.getLastErrorString());
                break;
            case HTTP_UPDATE_NO_UPDATES:
                Serial.println(F("[ota] no update"));
                break;
            case HTTP_UPDATE_OK:
                Serial.println(F("[ota] pull complete — rebooting"));
                otaReport(true, "");
                delay(300);
                ESP.restart();
                break;
            }
            return;
        }
    }
    http.end();
}

// Tell the server how it went (best effort; the node reboots on success).
inline void otaReport(bool ok, const String &msg)
{
    if (!net.wifi_up || cfg.server_url[0] == 0 || !cfg.ota_token[0]) return;
    char id[16];
    deviceId(cfg, id, sizeof(id));

    char url[160];
    snprintf(url, sizeof(url), "%s/api/v1/ota/ack", cfg.server_url);

    char payload[320];
    snprintf(payload, sizeof(payload),
             "{\"device\":\"%s\",\"key\":\"%s\",\"ok\":%s,\"version\":\"%s\",\"error\":\"%s\"}",
             id, cfg.ota_token, ok ? "true" : "false", FW_VERSION,
             msg.length() > 80 ? msg.substring(0, 80).c_str() : msg.c_str());

    HTTPClient http;
    if (!http.begin(url)) return;
    http.setTimeout(4000);
    http.addHeader("Content-Type", "application/json");
    http.POST(payload);
    http.end();
}

// ---------------------------------------------------------------------------
// lifecycle
// ---------------------------------------------------------------------------

// The push updater runs in its OWN FreeRTOS task: handleClient() called from
// the main loop is starved by DW1000Ranging.loop().
static void otaTask(void *)
{
    for (;;) {
        if (cfg.ota_enabled && net.wifi_up) g_ota.handleClient();
        vTaskDelay(pdMS_TO_TICKS(2));
    }
}

// The pull check + download MUST NOT run in the Arduino loop task: HTTPUpdate
// plus HTTPClient need far more than the 8 KB that task has, and the overflow
// shows up as
//   assert failed: xQueueSemaphoreTake queue.c:1554
//   Backtrace: ... |<-CORRUPTED
// (a corrupted backtrace is the classic stack-overflow signature). Give it a
// dedicated 16 KB stack instead.
static void otaPullTask(void *)
{
    vTaskDelay(pdMS_TO_TICKS(15000));       // let WiFi settle first
    for (;;) {
        otaCheckNow(false);
        vTaskDelay(pdMS_TO_TICKS(OTA_CHECK_INTERVAL_MS));
    }
}

inline void otaBegin()
{
    if (!cfg.ota_enabled || !net.wifi_up) return;
    static bool started = false;
    if (started) return;
    otaRegister();
    g_ota.begin(cfg.ota_port);
    xTaskCreatePinnedToCore(otaTask, "ota", 8192, nullptr, 2, nullptr, 0);
    xTaskCreatePinnedToCore(otaPullTask, "otapull", 16384, nullptr, 1, nullptr, 1);
    started = true;
    Serial.printf("[ota] updater on http://%s:%u/update (key required)\n",
                  WiFi.localIP().toString().c_str(), (unsigned)cfg.ota_port);
}

// Kept for compatibility with the main loop; the tasks do the real work.
inline void otaLoop() { }
